### ISSUE TITLE
No Printing on MF5750 with Ubuntu 16.04.3 LTS

### ISSUE THREAD

**Issue by waldo99** [ondrej-zary/carps-cups#12]
Thanks for a great driver. This has worked for me in the past for my MF5750.

Now I'm on LXLE (based on Ubuntu 16.04.3 LTS). Compiled properly (with a couple warnings I ignored) and installed. I created udev rules and mapped the printer correctly to /dev/canonMF5750 and set it to print to file:///dev/canonMF5750. However, after sending the print command, nothing happens. Printer doesn't react. Printer queue shows that the job was processed (rendering completed). Printer works fine in Windows. Tried the usual troubleshooting. Maybe something in a new cups package broke it?

Any help?

Thanks in advance!

**Comment by HeLiBloks** [comment]
I have the same Issue on 16.04.03 LTS and on the current raspbian release.
Hope this will be resolved as its a great printer

**Comment by ondrej-zary** [comment]
Does /dev/usb/lp0 exist before and after print attempt? Also try increasing LogLevel to debug in /etc/cups/cupsd.conf and check CUPS log files.

**Comment by HeLiBloks** [comment]
upon printing test page from cups web page I get these logs with ` cupsctl --debug-logging`

access_log:

 `localhost - - [04/Mar/2018:12:33:52 +0100] "POST /printers/Canon_MF5750 HTTP/1.1" 200 416 Print-Job successful-ok`

error_log:

`D [04/Mar/2018:12:34:15 +0100] [Client 110] HTTP_STATE_WAITING Closing for error 32 (Broken pipe)
D [04/Mar/2018:12:34:15 +0100] [Client 110] Closing connection.
D [04/Mar/2018:12:34:15 +0100] cupsdSetBusyState: newbusy="Dirty files", busy="Dirty files"
D [04/Mar/2018:12:34:15 +0100] [Client 110] Waiting for socket close.
I [04/Mar/2018:12:34:15 +0100] Expiring subscriptions...
D [04/Mar/2018:12:34:15 +0100] [Client 110] HTTP_STATE_WAITING Closing for error 32 (Broken pipe)
D [04/Mar/2018:12:34:15 +0100] [Client 110] Closing connection.
D [04/Mar/2018:12:34:15 +0100] cupsdSetBusyState: newbusy="Dirty files", busy="Dirty files"
I [04/Mar/2018:12:34:16 +0100] Expiring subscriptions...
I [04/Mar/2018:12:34:23 +0100] Saving job.cache...
I [04/Mar/2018:12:34:23 +0100] Saving subscriptions.conf...
D [04/Mar/2018:12:34:23 +0100] cupsdSetBusyState: newbusy="Not busy", busy="Dirty files"
I [04/Mar/2018:12:34:23 +0100] Expiring subscriptions...`

**Comment by ondrej-zary** [comment]
Just installed Ubuntu 16.04.4 (x64) for test and it works the same way as elsewhere. The default CUPS libusb backend prints one job, then printer displays something like "DATA ERROR". File /dev/usb/lp0 (or  a symlink created by udev) works fine.

**Comment by ondrej-zary** [comment]
Found a new workaround for the USB problem - blacklist the usblp module:
9240388521d3177c4192fcfcb0eaa3a531f6c719

**Comment by ondrej-zary** [comment]
Added carps.usb-quirks to make CUPS libusb backend work. No more file:// manual configuration, just add the printer and print: 8f01a98f28a61b38766b6a5bd39e0e298a527365

**Comment by waldo99** [comment]
Latest build works great. Can print multiple pages successfully. Thanks! It's wonderful when a developer continues to support even years after he wrote it. :)

**Comment by ondrej-zary** [comment]
I've just tested MF5730 and "delay-close" was not enough to print more than one job (no error on LCD but nothing more could be printed). Changed the workaround to "no-reattach" and it works now.
