### ISSUE TITLE
FAX L-150 or L-220 supported?

### ISSUE THREAD

**Issue by Chrisi-Bavaria** [ondrej-zary/carps-cups#18]
Hi, will the driver support I_SENSYS Fax L150 or the L-220?

I have a few of them but before starting maintenance/repair the hardware, I'd like to know if it's worth the effort.

Thx!

**Comment by ondrej-zary** [comment]
FAX-L150 (and also FAX-L160 and FAX-L170) are not CARPS printers. They use UFR II/UFRII LT data format and a driver (binary-only) is available from Canon.

FAX-L220 does not have PC connectivity. FAX-L295 has. According to the Windows driver, it's not a CARPS printer - it uses data format called MultiPASS.
