### ISSUE TITLE
Printer driver deprecation

### ISSUE THREAD

**Issue by HeLiBloks** [ondrej-zary/carps-cups#21]
I had to do the following to get cups to load the ppd file and be able to print on Fedora 40
```bash
cp ppd/mf5750.ppd /usr/share/cups/model/
lpadmin -p MF5750 -E -v 'usb://Canon/MF5750?serial=216271239260&interface=1' -m mf5750.ppd
lpadmin: Printer drivers are deprecated and will stop working in a future version of CUPS.
```

**Comment by ondrej-zary** [comment]
CUPS without drivers is useless - like many other Apple products.
It's time to fork CUPS to continue Linux printing support. Debian will probably have patches to keep drivers working.
