### ISSUE TITLE
carps-cups fails to build on Debian 7 i386

### ISSUE THREAD

**Issue by robertalks** [ondrej-zary/carps-cups#8]
Hi, trying to build this on my 32bit machine running Debian, but fails:

root@dhcp:~/pkg/git/carps-cups# make
gcc -Wall -Wextra --std=c99 -O2 carps-decode.c -o carps-decode
gcc -Wall -Wextra --std=c99 -O2 rastertocarps.c -o rastertocarps -lcupsimage -lcups
/tmp/ccLP1eGN.o: In function `encode_print_data':
rastertocarps.c:(.text+0xa18): undefined reference to `cupsRasterReadPixels'
/tmp/ccLP1eGN.o: In function `main':
rastertocarps.c:(.text.startup+0x91): undefined reference to `cupsRasterOpen'
rastertocarps.c:(.text.startup+0x4dc): undefined reference to `cupsRasterReadHeader2'
rastertocarps.c:(.text.startup+0x6ed): undefined reference to `cupsRasterClose'
collect2: error: ld returned 1 exit status
make: *** [rastertocarps] Error 1
root@dhcp:~/pkg/git/carps-cups# cat /etc/debian_version 
7.8
root@dhcp:~/pkg/git/carps-cups# ls^C
root@dhcp:~/pkg/git/carps-cups# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.8 (wheezy)
Release:	7.8
Codename:	wheezy
root@dhcp:~/pkg/git/carps-cups# dpkg -l |grep -E 'libcups2-dev|libcupsimage2-dev|cups-ppdc'
ii  cups-ppdc                          1.5.3-5+deb7u4                i386         Common UNIX Printing System(tm) - PPD manipulation utilities
ii  libcups2-dev                       1.5.3-5+deb7u4                i386         Common UNIX Printing System(tm) - Development files CUPS library
ii  libcupsimage2-dev                  1.5.3-5+deb7u4                i386         Common UNIX Printing System(tm) - Development files CUPS image library

Any ideas how to fix it?

**Comment by ondrej-zary** [comment]
It works for me:
```
$ git clone https://github.com/ondrej-zary/carps-cups.git
Cloning into 'carps-cups'...
remote: Counting objects: 482, done.
remote: Total 482 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (482/482), 97.58 KiB, done.
Resolving deltas: 100% (237/237), done.
$ cd carps-cups/
$ make
gcc -Wall -Wextra --std=c99 -O2 carps-decode.c -o carps-decode
gcc -Wall -Wextra --std=c99 -O2 rastertocarps.c -o rastertocarps -lcupsimage -lcups
ppdc carps.drv
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.8 (wheezy)
Release:        7.8
Codename:       wheezy
$ dpkg -l |grep -E 'libcups2-dev|libcupsimage2-dev|cups-ppdc'
ii  cups-ppdc                                   1.5.3-5+deb7u4                     i386         Common UNIX Printing System(tm) - PPD manipulation utilities
ii  libcups2-dev                                1.5.3-5+deb7u4                     i386         Common UNIX Printing System(tm) - Development files CUPS library
ii  libcupsimage2-dev                           1.5.3-5+deb7u4                     i386         Common UNIX Printing System(tm) - Development files CUPS image library
$ gcc --version
gcc (Debian 4.7.2-5) 4.7.2
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
$ uname -a
Linux medium 3.16.0-0.bpo.4-686-pae #1 SMP Debian 3.16.7-ckt2-1~bpo70+1 (2014-12-08) i686 GNU/Linux
```

**Comment by robertalks** [comment]
The first time I was able build the sources, but second time no.

**Comment by robertalks** [comment]
Borken machine :), thanks for the help.
